import localFont from "next/font/local";
import "./globals.css";
import { Joan } from '@next/font/google';

const joan = Joan({
  subsets: ['latin'], 
  weight: ['400'], 
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={`${joan.className} p-10`}>
      {children}
    </body>
  </html>
  );
}
